<?php

declare(strict_types = 1);

namespace Datalator\Popo;

/**
 * Code generated by POPO generator, do not edit.
 */
class CommandEnvironmentConfigurator
{
    /**
     * @var array
     */
    protected $data =  [
    'path' => null,
    'schemaName' => null,
    'dataName' => null,
    'schemaPath' => null,
    'dataPath' => null,
    'modules' =>
     [
     ],
    ];

    /**
     * @var array
     */
    protected $default =  [
    'path' => null,
    'schemaName' => null,
    'dataName' => null,
    'schemaPath' => null,
    'dataPath' => null,
    'modules' =>
     [
     ],
    ];

    /**
     * @var array
     */
    protected $propertyMapping =  [
    'path' => 'string',
    'schemaName' => 'string',
    'dataName' => 'string',
    'schemaPath' => 'string',
    'dataPath' => 'string',
    'modules' => 'array',
    ];

    /**
     * @var array
     */
    protected $collectionItems =  [
    'path' => '',
    'schemaName' => '',
    'dataName' => '',
    'schemaPath' => '',
    'dataPath' => '',
    'modules' => 'string',
    ];

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            return null;
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    /**
     * @return array
     */
    public function toArray(): array
    {
        $data = [];
        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = null;

            if (!isset($this->data[$key])) {
                continue;
            }

            $value = $this->data[$key];

            if ($this->collectionItems[$key] !== '') {
                if (\is_array($value) && \class_exists($this->collectionItems[$key])) {
                    foreach ($value as $popo) {
                        if (!\method_exists($popo, 'toArray')) {
                            continue;
                        }

                        $data[$key][] = $popo->toArray();
                    }
                }
            } else {
                $data[$key] = $value;
            }

            if (!\is_object($value) || !\method_exists($value, 'toArray')) {
                continue;
            }

            $data[$key] = $value->toArray();
        }

        return $data;
    }

    public function fromArray(array $data): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $result = [];
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key, $data)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (\method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                } else {
                    $result[$key] = $data[$key];
                }
            }

            if (!\is_array($result[$key]) || !\class_exists($type)) {
                continue;
            }

            $popo = new $type();
            if (\method_exists($popo, 'fromArray')) {
                $popo->fromArray($result[$key]);
            }
            $result[$key] = $popo;
        }

        $this->data = $result;

        return $this;
    }

    protected function isCollectionItem(string $key, array $data): bool
    {
        return $this->collectionItems[$key] !== '' &&
            \is_array($data[$key]) &&
            \class_exists($this->collectionItems[$key]);
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     *
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @throws \InvalidArgumentException
     *
     * @return void
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = \trim(\strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!\is_array($collection) || $type !== 'array') {
            throw new \InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    
    public function getPath(): ?string
    {
        return $this->popoGetValue('path');
    }

    /**
     * @param string|null $path
     *
     * @return self
     */
    public function setPath(?string $path): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('path', $path);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requirePath(): string
    {
        $this->assertPropertyValue('path');

        return (string)$this->popoGetValue('path');
    }

    public function getSchemaName(): ?string
    {
        return $this->popoGetValue('schemaName');
    }

    /**
     * @param string|null $schemaName
     *
     * @return self
     */
    public function setSchemaName(?string $schemaName): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('schemaName', $schemaName);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireSchemaName(): string
    {
        $this->assertPropertyValue('schemaName');

        return (string)$this->popoGetValue('schemaName');
    }

    public function getDataName(): ?string
    {
        return $this->popoGetValue('dataName');
    }

    /**
     * @param string|null $dataName
     *
     * @return self
     */
    public function setDataName(?string $dataName): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('dataName', $dataName);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireDataName(): string
    {
        $this->assertPropertyValue('dataName');

        return (string)$this->popoGetValue('dataName');
    }

    public function getSchemaPath(): ?string
    {
        return $this->popoGetValue('schemaPath');
    }

    /**
     * @param string|null $schemaPath
     *
     * @return self
     */
    public function setSchemaPath(?string $schemaPath): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('schemaPath', $schemaPath);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireSchemaPath(): string
    {
        $this->assertPropertyValue('schemaPath');

        return (string)$this->popoGetValue('schemaPath');
    }

    public function getDataPath(): ?string
    {
        return $this->popoGetValue('dataPath');
    }

    /**
     * @param string|null $dataPath
     *
     * @return self
     */
    public function setDataPath(?string $dataPath): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('dataPath', $dataPath);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireDataPath(): string
    {
        $this->assertPropertyValue('dataPath');

        return (string)$this->popoGetValue('dataPath');
    }

    /**
     * @return array|null
     */
    public function getModules(): ?array
    {
        return $this->popoGetValue('modules');
    }

    /**
     * @param array|null $modules
     *
     * @return self
     */
    public function setModules(?array $modules): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->popoSetValue('modules', $modules);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return array
     */
    public function requireModules(): array
    {
        $this->assertPropertyValue('modules');

        return (array)$this->popoGetValue('modules');
    }


    
    /**
     * @param string $modulesItem
     *
     * @return self
     */
    public function addModule(string $item): \Datalator\Popo\CommandEnvironmentConfigurator
    {
        $this->addCollectionItem('modules', $item);

        return $this;
    }
}
