<?php

declare(strict_types = 1);

namespace Datalator\Popo;

/**
 * Code generated by POPO generator, do not edit.
 */
class ModuleConfigurator 
{
    /**
     * @var array
     */
    protected $data = array (
  'name' => NULL,
  'tables' => 
  array (
  ),
);

    /**
     * @var array
     */
    protected $default = array (
  'name' => NULL,
  'tables' => 
  array (
  ),
);

    /**
    * @var array
    */
    protected $propertyMapping = array (
  'name' => 'string',
  'tables' => 'array',
);

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            return null;
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    /**
     * @return array
     */
    public function toArray(): array
    {
        $data = [];
        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = null;

            if (isset($this->data[$key])) {
                $value = $this->data[$key];
                $data[$key] = $value;

                if (\is_object($value) && \method_exists($value, 'toArray')) {
                    $data[$key] = $value->toArray();
                }
            }
        }

        return $data;
    }

    /**
     * @param array $data
     *
     * @return \Datalator\Popo\ModuleConfigurator
     */
    public function fromArray(array $data): \Datalator\Popo\ModuleConfigurator
    {
        $result = [];
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                $result[$key] = $data[$key];
            }

            if (\is_array($result[$key]) && \class_exists($type)) {
                $popo = new $type();
                if (\method_exists($popo, 'fromArray')) {
                    $popo->fromArray($result[$key]);
                }
                $result[$key] = $popo;
            }
        }

        $this->data = $result;

        return $this;
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    
    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->popoGetValue('name');
    }

    /**
     * @param string|null $name
     *
     * @return self
     */
    public function setName(?string $name): \Datalator\Popo\ModuleConfigurator
    {
        $this->popoSetValue('name', $name);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireName(): string
    {
        $this->assertPropertyValue('name');

        return (string)$this->popoGetValue('name');
    }

    /**
     * @return array|null
     */
    public function getTables(): ?array
    {
        return $this->popoGetValue('tables');
    }

    /**
     * @param array|null $tables
     *
     * @return self
     */
    public function setTables(?array $tables): \Datalator\Popo\ModuleConfigurator
    {
        $this->popoSetValue('tables', $tables);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return array
     */
    public function requireTables(): array
    {
        $this->assertPropertyValue('tables');

        return (array)$this->popoGetValue('tables');
    }

}
