<?php

declare(strict_types = 1);

namespace Datalator\Popo;

/**
 * Code generated by POPO generator, do not edit.
 */
class ReaderConfigurator 
{
    /**
     * @var array
     */
    protected $data = array (
  'source' => NULL,
  'identityValue' => NULL,
  'identityColumn' => 'id',
  'queryValue' => NULL,
  'queryColumn' => '*',
);

    /**
     * @var array
     */
    protected $default = array (
  'source' => NULL,
  'identityValue' => NULL,
  'identityColumn' => 'id',
  'queryValue' => NULL,
  'queryColumn' => '*',
);

    /**
    * @var array
    */
    protected $propertyMapping = array (
  'source' => 'string',
  'identityValue' => 'mixed',
  'identityColumn' => 'string',
  'queryValue' => 'string',
  'queryColumn' => 'string',
);

    /**
    * @var array
    */
    protected $collectionItems = array (
  'source' => '',
  'identityValue' => '',
  'identityColumn' => '',
  'queryValue' => '',
  'queryColumn' => '',
);

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            return null;
        }

        return $this->data[$property];
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;
    }

    /**
     * @return array
     */
    protected function getPropertyNames(): array
    {
        return \array_keys(
            $this->propertyMapping
        );
    }

    /**
     * @return array
     */
    public function toArray(): array
    {
        $data = [];
        foreach ($this->propertyMapping as $key => $type) {
            $data[$key] = null;

            if (isset($this->data[$key])) {
                $value = $this->data[$key];

                if ($this->collectionItems[$key] !== '') {
                    if (\is_array($value) && \class_exists($this->collectionItems[$key])) {
                        foreach ($value as $popo) {
                            if (\method_exists($popo, 'toArray')) {
                                $data[$key][] = $popo->toArray();
                            }
                        }
                    }
                } else {
                    $data[$key] = $value;
                }

                if (\is_object($value) && \method_exists($value, 'toArray')) {
                    $data[$key] = $value->toArray();
                }
            }
        }

        return $data;
    }

    public function fromArray(array $data): \Datalator\Popo\ReaderConfigurator
    {
        $result = [];
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = null;
            if (\array_key_exists($key, $this->default)) {
                $result[$key] = $this->default[$key];
            }
            if (\array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key, $data)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (\method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                } else {
                    $result[$key] = $data[$key];
                }
            }

            if (\is_array($result[$key]) && \class_exists($type)) {
                $popo = new $type();
                if (\method_exists($popo, 'fromArray')) {
                    $popo->fromArray($result[$key]);
                }
                $result[$key] = $popo;
            }
        }

        $this->data = $result;

        return $this;
    }

    protected function isCollectionItem(string $key, array $data): bool
    {
        return $this->collectionItems[$key] !== '' &&
            \is_array($data[$key]) &&
            \class_exists($this->collectionItems[$key]);
    }

    /**
     * @param string $property
     *
     * @throws \UnexpectedValueException
     * @return void
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new \UnexpectedValueException(\sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @throws \InvalidArgumentException
     * @return void
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = \trim(\strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!\is_array($collection) || $type !== 'array') {
            throw new \InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    
    /**
     * @return string|null
     */
    public function getSource(): ?string
    {
        return $this->popoGetValue('source');
    }

    /**
     * @param string|null $source
     *
     * @return self
     */
    public function setSource(?string $source): \Datalator\Popo\ReaderConfigurator
    {
        $this->popoSetValue('source', $source);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireSource(): string
    {
        $this->assertPropertyValue('source');

        return (string)$this->popoGetValue('source');
    }

    /**
     * @return mixed|null
     */
    public function getIdentityValue()
    {
        return $this->popoGetValue('identityValue');
    }

    /**
     * @param mixed|null $identityValue
     *
     * @return self
     */
    public function setIdentityValue($identityValue): \Datalator\Popo\ReaderConfigurator
    {
        $this->popoSetValue('identityValue', $identityValue);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return mixed
     */
    public function requireIdentityValue()
    {
        $this->assertPropertyValue('identityValue');

        return $this->popoGetValue('identityValue');
    }

    /**
     * @return string|null
     */
    public function getIdentityColumn(): ?string
    {
        return $this->popoGetValue('identityColumn');
    }

    /**
     * @param string|null $identityColumn
     *
     * @return self
     */
    public function setIdentityColumn(?string $identityColumn): \Datalator\Popo\ReaderConfigurator
    {
        $this->popoSetValue('identityColumn', $identityColumn);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireIdentityColumn(): string
    {
        $this->assertPropertyValue('identityColumn');

        return (string)$this->popoGetValue('identityColumn');
    }

    /**
     * @return string|null
     */
    public function getQueryValue(): ?string
    {
        return $this->popoGetValue('queryValue');
    }

    /**
     * @param string|null $queryValue
     *
     * @return self
     */
    public function setQueryValue(?string $queryValue): \Datalator\Popo\ReaderConfigurator
    {
        $this->popoSetValue('queryValue', $queryValue);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireQueryValue(): string
    {
        $this->assertPropertyValue('queryValue');

        return (string)$this->popoGetValue('queryValue');
    }

    /**
     * @return string|null
     */
    public function getQueryColumn(): ?string
    {
        return $this->popoGetValue('queryColumn');
    }

    /**
     * @param string|null $queryColumn
     *
     * @return self
     */
    public function setQueryColumn(?string $queryColumn): \Datalator\Popo\ReaderConfigurator
    {
        $this->popoSetValue('queryColumn', $queryColumn);

        return $this;
    }

    /**
     * @throws \UnexpectedValueException
     *
     * @return string
     */
    public function requireQueryColumn(): string
    {
        $this->assertPropertyValue('queryColumn');

        return (string)$this->popoGetValue('queryColumn');
    }


    
}
